# Generated by Django 2.0.3 on 2018-03-30 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('can_take_the_order', 'Can "Take The Order"'),)},
        ),
    ]
