# Generated by Django 2.0.3 on 2018-03-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180330_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypizzaprocess',
            name='table_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
