# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 11:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180330_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='chef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chefs', to=settings.AUTH_USER_MODEL),
        ),
    ]
